apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: db-setup
  name: db-setup
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-setup
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: db-setup
    spec:
      containers:
        - image: setup-db
          name: db-setup
      restartPolicy: Always
