version: '3'
services:
  my-app:
    image: 772992660467.dkr.ecr.us-east-1.amazonaws.com/my-app:latest
    ports:
      - 3000:3000
    depends_on:
      - "db-setup"
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123

    volumes:
      - db-data:/var/lib/mysql/data

  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin123
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - "mongodb"
  db-setup:
    build: 
      context: ./utility-app
      dockerfile: Dockerfile
    depends_on:
      - "mongodb"

volumes:
  db-data:
    driver: local
