---
- name: Run Docker Compose
  hosts: all
  become: yes

  vars:
    compose_file: ./docker-compose.yml

  tasks:
    - name: Check Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Check Docker Compose is installed
      pip:
        name: docker-compose
        state: present

    - name: Run Docker Compose
      community.docker.docker_compose:
        project_src: "{{ compose_file }}"
        state: present
      notify:
        - Restart Docker Compose

  handlers:
    - name: Restart Docker Compose
      community.docker.docker_compose:
        project_src: "{{ compose_file }}"
        state: restarted
